set(SOURCES
	include/OBSE/API.h
	include/OBSE/Impl/PCH.h
	include/OBSE/Interfaces.h
	include/OBSE/OBSE.h
	include/OBSE/Trampoline.h
	include/OBSE/Version.h
	include/RE/A/ACTION_FLAGS.h
	include/RE/A/ACTOR_BASE_DATA.h
	include/RE/A/ACTOR_LIFE_STATE.h
	include/RE/A/ACTOR_TYPE.h
	include/RE/A/AIDATA.h
	include/RE/A/AMMO_DATA.h
	include/RE/A/ActionObject.h
	include/RE/A/Actor.h
	include/RE/A/ActorDeathInfos.h
	include/RE/A/ActorValue.h
	include/RE/A/AlchemyItem.h
	include/RE/A/AlchemyItemData.h
	include/RE/B/BIPED_MODEL.h
	include/RE/B/BSCoreTypes.h
	include/RE/B/BSStringT.h
	include/RE/B/BSTCaseInsensitiveStringMap.h
	include/RE/B/BSTList.h
	include/RE/B/BaseExtraList.h
	include/RE/B/BaseFormComponent.h
	include/RE/B/BirthSign.h
	include/RE/C/CELL_MUSIC_TYPE.h
	include/RE/C/CHUNK_ID.h
	include/RE/C/CLASS_DATA.h
	include/RE/C/CREATURE_DATA.h
	include/RE/C/Character.h
	include/RE/C/CombatStyleData.h
	include/RE/C/CompilerName.h
	include/RE/C/Creature.h
	include/RE/D/DIALOGUE_DATA.h
	include/RE/D/DIALOGUE_EMOTION.h
	include/RE/E/EVUnpairingState.h
	include/RE/E/EffectItemList.h
	include/RE/E/EffectSetting.h
	include/RE/E/EffectShaderData.h
	include/RE/E/EnchantmentItem.h
	include/RE/E/EnchantmentItemData.h
	include/RE/E/ExpressionOperators.h
	include/RE/E/ExtraDataList.h
	include/RE/F/FACTION_DATA.h
	include/RE/F/FILE_HEADER.h
	include/RE/F/FORM.h
	include/RE/F/FORM_ENUM_STRING.h
	include/RE/F/FR2MatrixVTC.h
	include/RE/F/FormTypes.h
	include/RE/G/GAMEPAD_BUTTON.h
	include/RE/G/GameSettingCollection.h
	include/RE/H/HUDEffectIcon.h
	include/RE/H/HUDInfoMenu.h
	include/RE/H/HUDMainMenu.h
	include/RE/H/HUDReticle.h
	include/RE/I/IVPairableItem.h
	include/RE/I/IconArray.h
	include/RE/I/IngredientItem.h
	include/RE/I/IngredientItemData.h
	include/RE/I/Interface.h
	include/RE/I/InterfaceManager.h
	include/RE/IDs.h
	include/RE/M/MATERIAL_TYPE.h
	include/RE/M/MENU_CLASS.h
	include/RE/M/MagicCaster.h
	include/RE/M/MagicItem.h
	include/RE/M/MagicItemForm.h
	include/RE/M/MagicItemObject.h
	include/RE/M/MagicSystem.h
	include/RE/M/MagicTarget.h
	include/RE/M/MapMenu.h
	include/RE/M/MemoryManager.h
	include/RE/M/Menu.h
	include/RE/M/MenuConsole.h
	include/RE/M/MobileObject.h
	include/RE/M/ModifierList.h
	include/RE/N/NPC_DATA.h
	include/RE/N/NiPoint2.h
	include/RE/N/NiPoint3.h
	include/RE/N/NiPointer.h
	include/RE/N/NiRTTI.h
	include/RE/N/NiTArray.h
	include/RE/N/NiTDefaultAllocator.h
	include/RE/N/NiTList.h
	include/RE/N/NiTListBase.h
	include/RE/N/NiTListItem.h
	include/RE/N/NiTMap.h
	include/RE/N/NiTMapBase.h
	include/RE/N/NiTPointerAllocator.h
	include/RE/N/NiTPointerListBase.h
	include/RE/N/NiTPointerMap.h
	include/RE/N/NiTStringMap.h
	include/RE/NiRTTI_IDs.h
	include/RE/O/OBJ_APPA.h
	include/RE/O/OBJ_ARMO.h
	include/RE/O/OBJ_BOOK.h
	include/RE/O/OBJ_LAND.h
	include/RE/O/OBJ_LIGH.h
	include/RE/O/OBJ_REFR.h
	include/RE/O/OBJ_TREE.h
	include/RE/O/OBJ_WEAP.h
	include/RE/Oblivion.h
	include/RE/P/PACKAGE_DATA.h
	include/RE/P/PACKAGE_PROCEDURE_TYPE.h
	include/RE/P/PACK_SCHED_DATA.h
	include/RE/P/PackageList.h
	include/RE/P/PackageSchedule.h
	include/RE/P/PlayerCharacter.h
	include/RE/P/PlayerDeathInfos.h
	include/RE/Q/QUEST_DATA.h
	include/RE/R/RACE_DATA.h
	include/RE/R/REGION_DATA_ID.h
	include/RE/RTTI.h
	include/RE/RTTI_IDs.h
	include/RE/S/SCRIPT_BLOCK.h
	include/RE/S/SCRIPT_EFFECT_DATA.h
	include/RE/S/SCRIPT_ERROR.h
	include/RE/S/SCRIPT_FUNCTION.h
	include/RE/S/SCRIPT_HEADER.h
	include/RE/S/SCRIPT_LINE.h
	include/RE/S/SCRIPT_LOCAL.h
	include/RE/S/SCRIPT_OPERATOR.h
	include/RE/S/SCRIPT_OUTPUT.h
	include/RE/S/SCRIPT_PARAMETER.h
	include/RE/S/SCRIPT_PARAMETER_DEF.h
	include/RE/S/SCRIPT_PARAM_TYPE.h
	include/RE/S/SCRIPT_REFERENCED_OBJECT.h
	include/RE/S/SCRIPT_WORD.h
	include/RE/S/SIT_SLEEP_STATE.h
	include/RE/S/SKILL_ACTION.h
	include/RE/S/SKILL_BONUS.h
	include/RE/S/SKILL_DATA.h
	include/RE/S/SPECIALIZATION.h
	include/RE/S/Script.h
	include/RE/S/ScriptCompileData.h
	include/RE/S/ScriptCompiler.h
	include/RE/S/ScriptLocals.h
	include/RE/S/ScriptVariable.h
	include/RE/S/Setting.h
	include/RE/S/SettingCollection.h
	include/RE/S/SettingCollectionMap.h
	include/RE/S/SettingT.h
	include/RE/S/SkillLevel.h
	include/RE/S/SpellItem.h
	include/RE/S/SpellItemData.h
	include/RE/T/TESAIForm.h
	include/RE/T/TESActorBase.h
	include/RE/T/TESActorBaseData.h
	include/RE/T/TESAmmo.h
	include/RE/T/TESAnimation.h
	include/RE/T/TESAttackDamageForm.h
	include/RE/T/TESAttributes.h
	include/RE/T/TESBipedModelForm.h
	include/RE/T/TESBoundAnimObject.h
	include/RE/T/TESBoundObject.h
	include/RE/T/TESBoundTreeObject.h
	include/RE/T/TESChildCell.h
	include/RE/T/TESClass.h
	include/RE/T/TESClimate.h
	include/RE/T/TESCombatStyle.h
	include/RE/T/TESCondition.h
	include/RE/T/TESContainer.h
	include/RE/T/TESCreature.h
	include/RE/T/TESDataHandler.h
	include/RE/T/TESDescription.h
	include/RE/T/TESEffectShader.h
	include/RE/T/TESEnchantableForm.h
	include/RE/T/TESEyes.h
	include/RE/T/TESFaction.h
	include/RE/T/TESFile.h
	include/RE/T/TESFlora.h
	include/RE/T/TESForm.h
	include/RE/T/TESFullName.h
	include/RE/T/TESFurniture.h
	include/RE/T/TESGlobal.h
	include/RE/T/TESGrass.h
	include/RE/T/TESHair.h
	include/RE/T/TESHealthForm.h
	include/RE/T/TESIcon.h
	include/RE/T/TESIconTree.h
	include/RE/T/TESIdleForm.h
	include/RE/T/TESKey.h
	include/RE/T/TESLandTexture.h
	include/RE/T/TESLevCreature.h
	include/RE/T/TESLevItem.h
	include/RE/T/TESLevSpell.h
	include/RE/T/TESLeveledList.h
	include/RE/T/TESLoadScreen.h
	include/RE/T/TESMagicCasterForm.h
	include/RE/T/TESMagicTargetForm.h
	include/RE/T/TESMemContextForm.h
	include/RE/T/TESModel.h
	include/RE/T/TESModelAnim.h
	include/RE/T/TESModelList.h
	include/RE/T/TESModelTree.h
	include/RE/T/TESNPC.h
	include/RE/T/TESObject.h
	include/RE/T/TESObjectACTI.h
	include/RE/T/TESObjectANIO.h
	include/RE/T/TESObjectAPPA.h
	include/RE/T/TESObjectARMO.h
	include/RE/T/TESObjectBOOK.h
	include/RE/T/TESObjectCELL.h
	include/RE/T/TESObjectCLOT.h
	include/RE/T/TESObjectCONT.h
	include/RE/T/TESObjectDOOR.h
	include/RE/T/TESObjectLAND.h
	include/RE/T/TESObjectLIGH.h
	include/RE/T/TESObjectList.h
	include/RE/T/TESObjectMISC.h
	include/RE/T/TESObjectREFR.h
	include/RE/T/TESObjectSTAT.h
	include/RE/T/TESObjectTREE.h
	include/RE/T/TESObjectWEAP.h
	include/RE/T/TESPackage.h
	include/RE/T/TESPathGrid.h
	include/RE/T/TESProduceForm.h
	include/RE/T/TESQualityForm.h
	include/RE/T/TESQuest.h
	include/RE/T/TESQuestTarget.h
	include/RE/T/TESRace.h
	include/RE/T/TESRaceForm.h
	include/RE/T/TESReactionForm.h
	include/RE/T/TESRegion.h
	include/RE/T/TESRegionDataManager.h
	include/RE/T/TESRegionList.h
	include/RE/T/TESRoad.h
	include/RE/T/TESScriptableForm.h
	include/RE/T/TESSigilStone.h
	include/RE/T/TESSkill.h
	include/RE/T/TESSoulGem.h
	include/RE/T/TESSound.h
	include/RE/T/TESSoundFile.h
	include/RE/T/TESSpellList.h
	include/RE/T/TESSubSpace.h
	include/RE/T/TESTerrainLODManager.h
	include/RE/T/TESTexture.h
	include/RE/T/TESTextureList.h
	include/RE/T/TESTextureListArray.h
	include/RE/T/TESTopic.h
	include/RE/T/TESTopicInfo.h
	include/RE/T/TESUsesForm.h
	include/RE/T/TESValueForm.h
	include/RE/T/TESWaterForm.h
	include/RE/T/TESWeather.h
	include/RE/T/TESWeatherList.h
	include/RE/T/TESWeightForm.h
	include/RE/T/TESWorldSpace.h
	include/RE/T/TES_RETURN_CODE.h
	include/RE/T/TEXTURE_HAVOK_DATA.h
	include/RE/T/TOPIC_INFO_DATA.h
	include/RE/T/Tile.h
	include/RE/T/TileMenu.h
	include/RE/T/TileRect.h
	include/RE/V/VAnimationPairingComponentHandlers.h
	include/RE/V/VPreloadAssetsHandlers.h
	include/RE/VTABLE_IDs.h
	include/RE/W/WEAPON_TYPE.h
	include/RE/W/WORLD_MAP_DATA.h
	include/RE/W/WaterShaderData.h
	include/REL/ASM.h
	include/REL/Hook.h
	include/REL/HookObject.h
	include/REL/HookStore.h
	include/REL/IAT.h
	include/REL/ID.h
	include/REL/IDDB.h
	include/REL/Module.h
	include/REL/Offset.h
	include/REL/Offset2ID.h
	include/REL/REL.h
	include/REL/Relocation.h
	include/REL/Segment.h
	include/REL/Trampoline.h
	include/REL/Utility.h
	include/REL/Version.h
	include/REX/REX.h
	include/REX/REX/Enum.h
	include/REX/REX/EnumSet.h
	include/REX/REX/INI.h
	include/REX/REX/JSON.h
	include/REX/REX/LOG.h
	include/REX/REX/Setting.h
	include/REX/REX/Singleton.h
	include/REX/REX/TOML.h
	include/REX/W32.h
	include/REX/W32/ADVAPI32.h
	include/REX/W32/BASE.h
	include/REX/W32/BCRYPT.h
	include/REX/W32/COM.h
	include/REX/W32/COMPTR.h
	include/REX/W32/D3D.h
	include/REX/W32/D3D11.h
	include/REX/W32/D3D11_1.h
	include/REX/W32/D3D11_2.h
	include/REX/W32/D3D11_3.h
	include/REX/W32/D3D11_4.h
	include/REX/W32/D3DCOMPILER.h
	include/REX/W32/DBGHELP.h
	include/REX/W32/DINPUT.h
	include/REX/W32/DXGI.h
	include/REX/W32/DXGI_2.h
	include/REX/W32/DXGI_3.h
	include/REX/W32/DXGI_4.h
	include/REX/W32/DXGI_5.h
	include/REX/W32/DXGI_6.h
	include/REX/W32/KERNEL32.h
	include/REX/W32/NT.h
	include/REX/W32/OLE32.h
	include/REX/W32/SHELL32.h
	include/REX/W32/USER32.h
	include/REX/W32/VERSION.h
	include/REX/W32/XINPUT.h
	include/UE/A/AActor.h
	include/UE/A/ACharacter.h
	include/UE/A/AController.h
	include/UE/A/APawn.h
	include/UE/A/APlayerController.h
	include/UE/A/AVPairedPawn.h
	include/UE/B/BaseKeyFuncs.h
	include/UE/D/DefaultKeyFuncs.h
	include/UE/E/EAsyncExecution.h
	include/UE/E/EAutoPossessAI.h
	include/UE/E/EAutoReceiveInput.h
	include/UE/E/EClassCastFlags.h
	include/UE/E/EClassFlags.h
	include/UE/E/EComponentCreationMethod.h
	include/UE/E/EDynamicResolutionStateEvent.h
	include/UE/E/EEulerRotationOrder.h
	include/UE/E/EExprToken.h
	include/UE/E/EFindName.h
	include/UE/E/EFormID.h
	include/UE/E/EFrameHitchType.h
	include/UE/E/EFunctionFlags.h
	include/UE/E/EGetWorldErrorMode.h
	include/UE/E/EInternalObjectFlags.h
	include/UE/E/ELegacyMapMenuIcon.h
	include/UE/E/ELegacyMapMenuPage.h
	include/UE/E/ELevelTick.h
	include/UE/E/ELogVerbosity.h
	include/UE/E/EMovementMode.h
	include/UE/E/EName.h
	include/UE/E/ENameCase.h
	include/UE/E/ENamedThreads.h
	include/UE/E/ENetDormancy.h
	include/UE/E/ENetRole.h
	include/UE/E/EObjectFlags.h
	include/UE/E/EObjectFullNameFlags.h
	include/UE/E/EOblivionAnimGroup.h
	include/UE/E/EPackageExtension.h
	include/UE/E/EPhysicsReplicationMode.h
	include/UE/E/ESPMode.h
	include/UE/E/EScriptType.h
	include/UE/E/ESearchCase.h
	include/UE/E/ESpawnActorCollisionHandlingMethod.h
	include/UE/E/ETextFlag.h
	include/UE/E/ETickingGroup.h
	include/UE/E/ETransitionType.h
	include/UE/E/EVActorValues.h
	include/UE/E/EVBloodColor.h
	include/UE/E/EVBossCategory.h
	include/UE/F/FActorComponentTickFunction.h
	include/UE/F/FActorTickFunction.h
	include/UE/F/FAudioDeviceHandle.h
	include/UE/F/FBasedMovementInfo.h
	include/UE/F/FBlueprintCookedComponentInstancingData.h
	include/UE/F/FCellExteriorData.h
	include/UE/F/FCellInteriorData.h
	include/UE/F/FChunkedFixedUObjectArray.h
	include/UE/F/FColor.h
	include/UE/F/FCriticalSection.h
	include/UE/F/FCustomVersion.h
	include/UE/F/FCustomVersionContainer.h
	include/UE/F/FDebug.h
	include/UE/F/FDefaultAllocator.h
	include/UE/F/FDefaultBitArrayAllocator.h
	include/UE/F/FDefaultDelegateUserPolicy.h
	include/UE/F/FDefaultSetAllocator.h
	include/UE/F/FDefaultSparseArrayAllocator.h
	include/UE/F/FDelegateHandle.h
	include/UE/F/FDirectoryPath.h
	include/UE/F/FExec.h
	include/UE/F/FField.h
	include/UE/F/FFieldClass.h
	include/UE/F/FFieldPath.h
	include/UE/F/FFieldVariant.h
	include/UE/F/FFrame.h
	include/UE/F/FFrameRate.h
	include/UE/F/FGenericPlatformProcess.h
	include/UE/F/FGenericPlatformString.h
	include/UE/F/FGraphEvent.h
	include/UE/F/FGuid.h
	include/UE/F/FInputText.h
	include/UE/F/FIntPoint.h
	include/UE/F/FLegacyMapMenuIconProperties.h
	include/UE/F/FLegacyMapMenuLocalMapProperties.h
	include/UE/F/FLegacyMapMenuQuestProperties.h
	include/UE/F/FLegacyMapMenuTitleProperties.h
	include/UE/F/FLegacyMapMenuWorldMapProperties.h
	include/UE/F/FLinearColor.h
	include/UE/F/FLogScopedCategoryAndVerbosityOverride.h
	include/UE/F/FMemory.h
	include/UE/F/FMicrosoftPlatformString.h
	include/UE/F/FName.h
	include/UE/F/FNameEntry.h
	include/UE/F/FNameEntryAllocator.h
	include/UE/F/FNameEntryHandle.h
	include/UE/F/FNameEntryId.h
	include/UE/F/FNamePool.h
	include/UE/F/FNamePoolShardBase.h
	include/UE/F/FNetworkNotify.h
	include/UE/F/FNotThreadSafeNotCheckedDelegateUserPolicy.h
	include/UE/F/FObjectPostSaveContext.h
	include/UE/F/FObjectPostSaveRootContext.h
	include/UE/F/FObjectPreSaveContext.h
	include/UE/F/FObjectPreSaveRootContext.h
	include/UE/F/FObjectPtr.h
	include/UE/F/FObjectSubsystemCollection.h
	include/UE/F/FOblivionNPCFaceGenData.h
	include/UE/F/FOutParmRec.h
	include/UE/F/FOutputDevice.h
	include/UE/F/FPackageFileVersion.h
	include/UE/F/FPackagePath.h
	include/UE/F/FParse.h
	include/UE/F/FPathGridPointData.h
	include/UE/F/FPathGridPointDataArray.h
	include/UE/F/FPlatformString.h
	include/UE/F/FPoseSnapshot.h
	include/UE/F/FRWLock.h
	include/UE/F/FRaceData.h
	include/UE/F/FRawObjectIterator.h
	include/UE/F/FRenderCommandFence.h
	include/UE/F/FRepAttachment.h
	include/UE/F/FRepMovement.h
	include/UE/F/FRepRootMotionMontage.h
	include/UE/F/FRootMotionMovementParams.h
	include/UE/F/FRootMotionSourceGroup.h
	include/UE/F/FRootMotionSourceSettings.h
	include/UE/F/FScopeLock.h
	include/UE/F/FScreenMessageString.h
	include/UE/F/FSelfRegisteringExec.h
	include/UE/F/FSetElementId.h
	include/UE/F/FSoftClassPath.h
	include/UE/F/FSoftObjectPath.h
	include/UE/F/FSoftObjectPtr.h
	include/UE/F/FSparseDelegate.h
	include/UE/F/FStaticConstructObjectParameters.h
	include/UE/F/FStaticSelfRegisteringExec.h
	include/UE/F/FString.h
	include/UE/F/FStructBaseChain.h
	include/UE/F/FStructuredArchive.h
	include/UE/F/FStructuredArchiveArray.h
	include/UE/F/FStructuredArchiveMap.h
	include/UE/F/FStructuredArchiveRecord.h
	include/UE/F/FStructuredArchiveSlot.h
	include/UE/F/FStructuredArchiveSlotBase.h
	include/UE/F/FStructuredArchiveStream.h
	include/UE/F/FTESWeatherList.h
	include/UE/F/FText.h
	include/UE/F/FThreadSafeCounter.h
	include/UE/F/FTickFunction.h
	include/UE/F/FTimerHandle.h
	include/UE/F/FTopLevelAssetPath.h
	include/UE/F/FUObjectArray.h
	include/UE/F/FUObjectItem.h
	include/UE/F/FURL.h
	include/UE/F/FVector.h
	include/UE/F/FVector2.h
	include/UE/F/FVector_NetQuantize.h
	include/UE/F/FWaterShaderData.h
	include/UE/F/FWeakObjectPtr.h
	include/UE/F/FWorldMapData.h
	include/UE/F/FWorldMapLandscapeInfo.h
	include/UE/F/FWorldMapLandscapeSettings.h
	include/UE/F/FieldNotification_FFieldId.h
	include/UE/F/FieldNotification_FFieldMulticastDelegate.h
	include/UE/F/FieldNotification_IClassDescriptor.h
	include/UE/I/IBlueprintPropertyGuidProvider.h
	include/UE/I/IDelegateInstance.h
	include/UE/I/IInterface.h
	include/UE/I/IInterface_AssetUserData.h
	include/UE/I/INavAgentInterface.h
	include/UE/I/INotifyFieldValueChanged.h
	include/UE/I/IPairingGate.h
	include/UE/I/IReactToFreezeInterface.h
	include/UE/I/ITextData.h
	include/UE/I/IVAudioPlayable.h
	include/UE/I/IVPhysicsControllable.h
	include/UE/I/IVTransformPairable.h
	include/UE/I/IWorldPartitionStreamingSourceProvider.h
	include/UE/M/MVVM_FMVVMFieldNotificationDelegates.h
	include/UE/S/SharedPointerInternals.h
	include/UE/T/TAlignedBytes.h
	include/UE/T/TAllocatorFixedSizeFreeList.h
	include/UE/T/TAllocatorTraits.h
	include/UE/T/TArray.h
	include/UE/T/TBaseDynamicDelegate.h
	include/UE/T/TBaseDynamicMulticastDelegate.h
	include/UE/T/TBitArray.h
	include/UE/T/TBitsToSizeType.h
	include/UE/T/TCast.h
	include/UE/T/TChooseClass.h
	include/UE/T/TCopyQualifiersAndRefsFromTo.h
	include/UE/T/TCopyQualifiersFromTo.h
	include/UE/T/TDefaultDelete.h
	include/UE/T/TDefaultMapHashableKeyFuncs.h
	include/UE/T/TDefaultMapKeyFuncs.h
	include/UE/T/TDelegate.h
	include/UE/T/TDelegateAccessHandlerBase.h
	include/UE/T/TDelegateBase.h
	include/UE/T/TEnumAsByte.h
	include/UE/T/TFieldPath.h
	include/UE/T/TFunction.h
	include/UE/T/TIndirectArray.h
	include/UE/T/TInlineAllocator.h
	include/UE/T/TInlineSetAllocator.h
	include/UE/T/TInlineSparseArrayAllocator.h
	include/UE/T/TIntPoint.h
	include/UE/T/TIntegerSequence.h
	include/UE/T/TMap.h
	include/UE/T/TMapBase.h
	include/UE/T/TMulticastDelegate.h
	include/UE/T/TMulticastDelegateBase.h
	include/UE/T/TMulticastScriptDelegate.h
	include/UE/T/TNamePoolShard.h
	include/UE/T/TObjectIteratorBase.h
	include/UE/T/TObjectPtr.h
	include/UE/T/TPair.h
	include/UE/T/TPayload.h
	include/UE/T/TPersistentObjectPtr.h
	include/UE/T/TPlacementNewer.h
	include/UE/T/TQuat.h
	include/UE/T/TRefCountPtr.h
	include/UE/T/TRotator.h
	include/UE/T/TScriptDelegate.h
	include/UE/T/TSet.h
	include/UE/T/TSetAllocator.h
	include/UE/T/TSetElement.h
	include/UE/T/TSetElementBase.h
	include/UE/T/TSharedFromThis.h
	include/UE/T/TSharedPtr.h
	include/UE/T/TSharedRef.h
	include/UE/T/TSizedDefaultAllocator.h
	include/UE/T/TSizedHeapAllocator.h
	include/UE/T/TSizedInlineAllocator.h
	include/UE/T/TSoftClassPtr.h
	include/UE/T/TSoftObjectPtr.h
	include/UE/T/TSortableMapBase.h
	include/UE/T/TSparseArray.h
	include/UE/T/TSparseArrayAllocator.h
	include/UE/T/TSparseArrayElementOrFreeListLink.h
	include/UE/T/TSparseDynamicDelegate.h
	include/UE/T/TStringBuilder.h
	include/UE/T/TSubclassOf.h
	include/UE/T/TTemplate.h
	include/UE/T/TTransform.h
	include/UE/T/TTuple.h
	include/UE/T/TTypeCompatibleBytes.h
	include/UE/T/TTypeTraits.h
	include/UE/T/TUniqueFunction.h
	include/UE/T/TUniquePtr.h
	include/UE/T/TVector.h
	include/UE/T/TVector2.h
	include/UE/T/TWeakObjectPtr.h
	include/UE/T/TWeakPtr.h
	include/UE/U/UActorComponent.h
	include/UE/U/UAltarCheatManager.h
	include/UE/U/UBlueprintFunctionLibrary.h
	include/UE/U/UBlueprintGeneratedClass.h
	include/UE/U/UCheatManager.h
	include/UE/U/UClass.h
	include/UE/U/UEngine.h
	include/UE/U/UField.h
	include/UE/U/UFunction.h
	include/UE/U/UGameplayStatics.h
	include/UE/U/UInterface.h
	include/UE/U/UKismetSystemLibrary.h
	include/UE/U/UMVVMViewModelBase.h
	include/UE/U/UObject.h
	include/UE/U/UObjectBase.h
	include/UE/U/UObjectBaseUtility.h
	include/UE/U/UObjectGlobals.h
	include/UE/U/UObjectHash.h
	include/UE/U/UPackage.h
	include/UE/U/UStruct.h
	include/UE/U/UTESBaseFormComponent.h
	include/UE/U/UTESCell.h
	include/UE/U/UTESClass.h
	include/UE/U/UTESClimate.h
	include/UE/U/UTESFaction.h
	include/UE/U/UTESForm.h
	include/UE/U/UTESGameSetting.h
	include/UE/U/UTESHair.h
	include/UE/U/UTESIdleForm.h
	include/UE/U/UTESObject.h
	include/UE/U/UTESObjectREFR.h
	include/UE/U/UTESPackage.h
	include/UE/U/UTESQuest.h
	include/UE/U/UTESRace.h
	include/UE/U/UTESRegion.h
	include/UE/U/UTESScript.h
	include/UE/U/UTESTopic.h
	include/UE/U/UTESTopicInfo.h
	include/UE/U/UTESWaterForm.h
	include/UE/U/UTESWeather.h
	include/UE/U/UTESWorldSpace.h
	include/UE/U/UVMapMenuViewModel.h
	include/UE/U/UVMapPageViewModel.h
	include/UE/U/UVTESObjectRefComponent.h
	include/UE/U/UVViewModelBase.h
	include/UE/U/UWorld.h
	include/UE/U/UWorldProxy.h
	include/UE/Unreal.h
	include/UE/UnrealGlobal.h
	include/UE/UnrealMacro.h
	include/UE/V/VHandlerClass.h
	include/UE/V/VOblivionUEPairingGate.h
	include/UE/V/VPairingData_IPairingData.h
	include/UE/V/VPairingData_VTransform.h
	include/UE/V/VPairingEntry.h
	include/UE/V/VPairingFlowManager.h
	src/OBSE/API.cpp
	src/OBSE/Impl/PCH.cpp
	src/OBSE/Interfaces.cpp
	src/RE/F/FormTypes.cpp
	src/RE/N/NiPoint2.cpp
	src/RE/N/NiPoint3.cpp
	src/RE/Oblivion.cpp
	src/RE/S/Setting.cpp
	src/RE/T/Tile.cpp
	src/REL/HookObject.cpp
	src/REL/HookStore.cpp
	src/REL/IAT.cpp
	src/REL/IDDB.cpp
	src/REL/Module.cpp
	src/REL/Trampoline.cpp
	src/REL/Utility.cpp
	src/REL/Version.cpp
	src/REX/REX.cpp
	src/REX/W32.cpp
	src/UE/F/FNameEntryId.cpp
	src/UE/Unreal.cpp
)
