set(SOURCES
	include/OBSE/API.h
	include/OBSE/Impl/PCH.h
	include/OBSE/Interfaces.h
	include/OBSE/OBSE.h
	include/OBSE/Trampoline.h
	include/OBSE/Version.h
	include/RE/B/BSCoreTypes.h
	include/RE/B/BSStringT.h
	include/RE/B/BSTCaseInsensitiveStringMap.h
	include/RE/B/BSTList.h
	include/RE/B/BaseFormComponent.h
	include/RE/B/BaseKeyFuncs.h
	include/RE/D/DefaultKeyFuncs.h
	include/RE/F/FDefaultBitArrayAllocator.h
	include/RE/F/FDefaultSetAllocator.h
	include/RE/F/FDefaultSparseArrayAllocator.h
	include/RE/F/FExec.h
	include/RE/F/FName.h
	include/RE/F/FNameEntryId.h
	include/RE/F/FNetworkNotify.h
	include/RE/F/FORM.h
	include/RE/F/FORM_ENUM_STRING.h
	include/RE/F/FObjectPostSaveContext.h
	include/RE/F/FObjectPostSaveRootContext.h
	include/RE/F/FObjectPreSaveContext.h
	include/RE/F/FObjectPreSaveRootContext.h
	include/RE/F/FObjectPtr.h
	include/RE/F/FPathGridPointData.h
	include/RE/F/FPathGridPointDataArray.h
	include/RE/F/FSetElementId.h
	include/RE/F/FString.h
	include/RE/F/FStructuredArchiveRecord.h
	include/RE/F/FURL.h
	include/RE/F/FormTypes.h
	include/RE/G/GameSettingCollection.h
	include/RE/IDs.h
	include/RE/M/MemoryManager.h
	include/RE/M/MenuConsole.h
	include/RE/N/NiRTTI.h
	include/RE/N/NiTDefaultAllocator.h
	include/RE/N/NiTList.h
	include/RE/N/NiTListBase.h
	include/RE/N/NiTListItem.h
	include/RE/N/NiTMap.h
	include/RE/N/NiTMapBase.h
	include/RE/N/NiTPointerAllocator.h
	include/RE/N/NiTPointerListBase.h
	include/RE/N/NiTPointerMap.h
	include/RE/N/NiTStringMap.h
	include/RE/NiRTTI_IDs.h
	include/RE/Oblivion.h
	include/RE/RTTI.h
	include/RE/RTTI_IDs.h
	include/RE/S/Setting.h
	include/RE/S/SettingCollection.h
	include/RE/S/SettingCollectionMap.h
	include/RE/S/SettingT.h
	include/RE/S/SharedPointerInternals.h
	include/RE/T/TAlignedBytes.h
	include/RE/T/TArray.h
	include/RE/T/TBitArray.h
	include/RE/T/TDefaultMapHashableKeyFuncs.h
	include/RE/T/TDefaultMapKeyFuncs.h
	include/RE/T/TESBoundAnimObject.h
	include/RE/T/TESBoundObject.h
	include/RE/T/TESForm.h
	include/RE/T/TESObject.h
	include/RE/T/TESObjectList.h
	include/RE/T/TIntegerSequence.h
	include/RE/T/TMap.h
	include/RE/T/TMapBase.h
	include/RE/T/TObjectPtr.h
	include/RE/T/TRotator.h
	include/RE/T/TSet.h
	include/RE/T/TSetAllocator.h
	include/RE/T/TSetElement.h
	include/RE/T/TSetElementBase.h
	include/RE/T/TSharedPtr.h
	include/RE/T/TSizedDefaultAllocator.h
	include/RE/T/TSizedHeapAllocator.h
	include/RE/T/TSizedInlineAllocator.h
	include/RE/T/TSortableMapBase.h
	include/RE/T/TSparseArray.h
	include/RE/T/TSparseArrayAllocator.h
	include/RE/T/TSparseArrayElementOrFreeListLink.h
	include/RE/T/TSubclassOf.h
	include/RE/T/TTuple.h
	include/RE/T/TTypeCompatibleBytes.h
	include/RE/T/TVector.h
	include/RE/U/UBlueprintFunctionLibrary.h
	include/RE/U/UCheatManager.h
	include/RE/U/UEngine.h
	include/RE/U/UGameplayStatics.h
	include/RE/U/UObject.h
	include/RE/U/UObjectBase.h
	include/RE/U/UObjectBaseUtility.h
	include/RE/U/UWorld.h
	include/RE/VTABLE_IDs.h
	include/REL/ASM.h
	include/REL/Hook.h
	include/REL/HookObject.h
	include/REL/HookStore.h
	include/REL/IAT.h
	include/REL/ID.h
	include/REL/IDDB.h
	include/REL/Module.h
	include/REL/Offset.h
	include/REL/Offset2ID.h
	include/REL/REL.h
	include/REL/Relocation.h
	include/REL/Segment.h
	include/REL/Trampoline.h
	include/REL/Utility.h
	include/REL/Version.h
	include/REX/REX.h
	include/REX/REX/Enum.h
	include/REX/REX/EnumSet.h
	include/REX/REX/INI.h
	include/REX/REX/JSON.h
	include/REX/REX/LOG.h
	include/REX/REX/Setting.h
	include/REX/REX/Singleton.h
	include/REX/REX/TOML.h
	include/REX/W32.h
	include/REX/W32/ADVAPI32.h
	include/REX/W32/BASE.h
	include/REX/W32/BCRYPT.h
	include/REX/W32/COM.h
	include/REX/W32/COMPTR.h
	include/REX/W32/D3D.h
	include/REX/W32/D3D11.h
	include/REX/W32/D3D11_1.h
	include/REX/W32/D3D11_2.h
	include/REX/W32/D3D11_3.h
	include/REX/W32/D3D11_4.h
	include/REX/W32/D3DCOMPILER.h
	include/REX/W32/DBGHELP.h
	include/REX/W32/DINPUT.h
	include/REX/W32/DXGI.h
	include/REX/W32/DXGI_2.h
	include/REX/W32/DXGI_3.h
	include/REX/W32/DXGI_4.h
	include/REX/W32/DXGI_5.h
	include/REX/W32/DXGI_6.h
	include/REX/W32/KERNEL32.h
	include/REX/W32/NT.h
	include/REX/W32/OLE32.h
	include/REX/W32/SHELL32.h
	include/REX/W32/USER32.h
	include/REX/W32/VERSION.h
	include/REX/W32/XINPUT.h
	src/OBSE/API.cpp
	src/OBSE/Impl/PCH.cpp
	src/OBSE/Interfaces.cpp
	src/RE/F/FormTypes.cpp
	src/RE/Oblivion.cpp
	src/RE/S/Setting.cpp
	src/REL/HookObject.cpp
	src/REL/HookStore.cpp
	src/REL/IAT.cpp
	src/REL/IDDB.cpp
	src/REL/Module.cpp
	src/REL/Trampoline.cpp
	src/REL/Utility.cpp
	src/REL/Version.cpp
	src/REX/REX.cpp
	src/REX/W32.cpp
)
