set(SOURCES
	include/OBSE/API.h
	include/OBSE/Impl/PCH.h
	include/OBSE/Interfaces.h
	include/OBSE/OBSE.h
	include/OBSE/Trampoline.h
	include/OBSE/Version.h
	include/RE/B/BSTCaseInsensitiveStringMap.h
	include/RE/G/GameSettingCollection.h
	include/RE/IDs.h
	include/RE/M/MemoryManager.h
	include/RE/N/NiTDefaultAllocator.h
	include/RE/N/NiTMap.h
	include/RE/N/NiTMapBase.h
	include/RE/N/NiTStringMap.h
	include/RE/NiRTTI_IDs.h
	include/RE/Oblivion.h
	include/RE/RTTI.h
	include/RE/RTTI_IDs.h
	include/RE/S/Setting.h
	include/RE/S/SettingCollection.h
	include/RE/S/SettingCollectionMap.h
	include/RE/S/SettingT.h
	include/RE/VTABLE_IDs.h
	src/OBSE/API.cpp
	src/OBSE/Impl/PCH.cpp
	src/OBSE/Interfaces.cpp
	src/RE/Oblivion.cpp
	src/RE/S/Setting.cpp
)
